server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://121.36.4.131:26000/db_tpcc?ApplicationName=app1
    driver-class-name: org.postgresql.Driver
    username: gary
    password: GRgaorui142993
mybatis:
  type-aliases-package: com.gr.pojo
  mapper-locations: classpath:mybatis/*.xml