server:
  port: 8888
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/partner_matching
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: gaorui030213
mybatis:
  type-aliases-package: com.seproject.pojo
#  mapper-locations: classpath:mybatis/*.xml